import Navbar from "@/components/Homepage/Navbar";
import { inter } from "./fonts";
import "./globals.css";
import AuthProvider from "@/services/AuthProvider";

export const metadata = {
  title: "FoodFarm - Grocery Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
