import Navbar from "@/components/Homepage/Navbar";
import { inter } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "FoodFarm - Grocery Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
