import AdminPanelLayout from "@/components/admin-dashboard/admin-panel-layout";
import { ContentLayout } from "@/components/admin-dashboard/content-layout";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { UserContentTable } from "@/components/users/UserContent";
import Link from "next/link";

export const metadata = {
  title: "FoodFarm - Dashboard",
  description: "Generated by create next app",
};

const UsersPage = () => {
  return (
    <AdminPanelLayout>
      <ContentLayout title="Users">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link href="/">Home</Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Users</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
        <UserContentTable />
      </ContentLayout>
    </AdminPanelLayout>
  );
};

export default UsersPage;
